# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce627a6e73af914f850bec93ab794bde6d0f1fff7c6ae31c5d05da33a74ff751d10d4f55d8d012c94449b8029d925f42560c458a7a8d9b42776763b63f7f4eab

test:
  secret_key_base: 24f7d90fc4d10c9260413c2001cb1c25d5bbf24e4e939b348d89aca96771662b8dad135448c912269a14d826db0bc64bb331085a4148c3c9150a4ac949bc6385

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
